#!/usr/bin/env python3
"""Generate src/unicode_data.inc: codepoint-class ranges for the o200k
pre-tokenizer regex.

Classes (bitmask):
  LU = Lu | Lt   (uppercase-ish letters; Lt titlecase groups with Lu in the
                  regex's first bracket)
  LL = Ll
  LX = Lm | Lo   (caseless letters: members of BOTH bracket classes)
  M  = Mn | Mc | Me
  N  = Nd | Nl | No
  WS = regex \\s = UCD White_Space (fixed 25-codepoint list; NOT Python
       str.isspace, which differs on e.g. \\x1c-\\x1f)

The regex classes are composed in the scanner:
  \\p{L}    = LU | LL | LX
  UPPERISH  = LU | LX | M    ([\\p{Lu}\\p{Lt}\\p{Lm}\\p{Lo}\\p{M}])
  LOWERISH  = LL | LX | M    ([\\p{Ll}\\p{Lm}\\p{Lo}\\p{M}])

Output is committed; regenerate with any Python >= 3.10 (table contents
depend on the unicodedata version — pin noted in the header comment).
CI check: regenerating must reproduce the committed file byte-identically.
"""
import sys
import unicodedata

MASK = {"LU": 1, "LL": 2, "LX": 4, "M": 8, "N": 16, "WS": 32}

CAT_TO_MASK = {
    "Lu": MASK["LU"], "Lt": MASK["LU"],
    "Ll": MASK["LL"],
    "Lm": MASK["LX"], "Lo": MASK["LX"],
    "Mn": MASK["M"], "Mc": MASK["M"], "Me": MASK["M"],
    "Nd": MASK["N"], "Nl": MASK["N"], "No": MASK["N"],
}

# UCD PropList White_Space (stable since Unicode 6); regex \s in oniguruma /
# Rust regex with unicode == this set.
WHITE_SPACE = [
    *range(0x0009, 0x000E), 0x0020, 0x0085, 0x00A0, 0x1680,
    *range(0x2000, 0x200B), 0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
]


def main():
    classes = {}
    for cp in range(0x110000):
        m = CAT_TO_MASK.get(unicodedata.category(chr(cp)), 0)
        if m:
            classes[cp] = m
    for cp in WHITE_SPACE:
        classes[cp] = classes.get(cp, 0) | MASK["WS"]

    # coalesce into (lo, hi, mask) ranges
    ranges = []
    for cp in sorted(classes):
        m = classes[cp]
        if ranges and ranges[-1][1] == cp - 1 and ranges[-1][2] == m:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, m])

    out = sys.stdout
    out.write("// GENERATED by scripts/gen_unicode.py — do not edit.\n")
    out.write(f"// unicodedata {unicodedata.unidata_version}, {len(ranges)} ranges.\n")
    out.write("// masks: LU=1 LL=2 LX=4 M=8 N=16 WS=32 (see gen_unicode.py)\n")
    out.write("static const struct { uint32_t lo, hi; uint8_t mask; } unicode_ranges[] = {\n")
    for lo, hi, m in ranges:
        out.write(f"    {{0x{lo:05X}, 0x{hi:05X}, {m}}},\n")
    out.write("};\n")


if __name__ == "__main__":
    main()
